#arithmatic operator (+, -, *, /, %, ^, %%, %/%)
#assignment operator (<-, <<-)
#relational operator (<, >, <=, >=, ==, !=)
#logical operator (&, |, &&, ||, !)
#miscellaneous operator (:, %in%, %*%)